// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANJxZs_02p-b2mZ8BgqlkSqNeXqDMXEIA',
    appId: '1:967345300269:web:b26951ccd562ecde60a9a4',
    messagingSenderId: '967345300269',
    projectId: 'animeinfo-41c81',
    authDomain: 'animeinfo-41c81.firebaseapp.com',
    storageBucket: 'animeinfo-41c81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3E8HGWyGJWdES3vY5Fa6CFPvO1yK6LD0',
    appId: '1:967345300269:android:ab522aa828153f2560a9a4',
    messagingSenderId: '967345300269',
    projectId: 'animeinfo-41c81',
    storageBucket: 'animeinfo-41c81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnKI8rRC1cXtetXGoj7CB7sLRKCniS384',
    appId: '1:967345300269:ios:c979b6782f0d949e60a9a4',
    messagingSenderId: '967345300269',
    projectId: 'animeinfo-41c81',
    storageBucket: 'animeinfo-41c81.firebasestorage.app',
    iosBundleId: 'com.example.animeinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnKI8rRC1cXtetXGoj7CB7sLRKCniS384',
    appId: '1:967345300269:ios:c979b6782f0d949e60a9a4',
    messagingSenderId: '967345300269',
    projectId: 'animeinfo-41c81',
    storageBucket: 'animeinfo-41c81.firebasestorage.app',
    iosBundleId: 'com.example.animeinfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANJxZs_02p-b2mZ8BgqlkSqNeXqDMXEIA',
    appId: '1:967345300269:web:d685f2b9790cda2a60a9a4',
    messagingSenderId: '967345300269',
    projectId: 'animeinfo-41c81',
    authDomain: 'animeinfo-41c81.firebaseapp.com',
    storageBucket: 'animeinfo-41c81.firebasestorage.app',
  );
}
